name: amore
description: "Amore - 深度連結的約會應用程式，專為香港市場設計"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI 和動畫
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  
  # 狀態管理
  flutter_riverpod: ^2.4.9
  
  # 路由
  go_router: ^12.1.3
  
  # Firebase 服務 - 使用穩定兼容版本
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_app_check: ^0.1.2+7
  # firebase_app_distribution: ^1.1.1  # 暫時註解掉，使用 Firebase CLI 進行分發
  
  # 網絡和 API
  dio: ^5.3.4
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  
  # 本地存儲
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 圖片處理
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  image_cropper: ^9.1.0
  flutter_image_compress: ^2.1.0
  image: ^4.1.3
  
  # 地理位置
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # 視頻通話
  # agora_rtc_engine: ^6.3.0
  permission_handler: ^11.1.0
  
  # 音頻處理
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.5
  
  # 工具類
  intl: ^0.20.2
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  path: ^1.8.3
  
  # 支付
  in_app_purchase: ^3.1.11
  
  # 社交媒體整合
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.1.6
  
  # 其他
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # 代碼生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # 資產配置
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    - assets/fonts/
  
  # 字體配置
  fonts:
    - family: NotoSansHK
      fonts:
        - asset: assets/fonts/NotoSansHK-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansHK-Bold.ttf
          weight: 700 