// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvL743BpjtCYCTm8P_Ci26A_5XcrI2yd8',
    appId: '1:380903609347:web:85afa5846628b01860aa36',
    messagingSenderId: '380903609347',
    projectId: 'amore-hk',
    authDomain: 'amore-hk.firebaseapp.com',
    storageBucket: 'amore-hk.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvL743BpjtCYCTm8P_Ci26A_5XcrI2yd8',
    appId: '1:380903609347:android:85afa5846628b01860aa36',
    messagingSenderId: '380903609347',
    projectId: 'amore-hk',
    storageBucket: 'amore-hk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd5sXYEVRvJvhGYcI-fvx5zCmL_ZpHggQ',
    appId: '1:380903609347:ios:84610dd44cb55f2e60aa36',
    messagingSenderId: '380903609347',
    projectId: 'amore-hk',
    storageBucket: 'amore-hk.firebasestorage.app',
    iosBundleId: 'com.amore.hk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd5sXYEVRvJvhGYcI-fvx5zCmL_ZpHggQ',
    appId: '1:380903609347:macos:84610dd44cb55f2e60aa36',
    messagingSenderId: '380903609347',
    projectId: 'amore-hk',
    storageBucket: 'amore-hk.firebasestorage.app',
    iosBundleId: 'com.amore.hk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvL743BpjtCYCTm8P_Ci26A_5XcrI2yd8',
    appId: '1:380903609347:windows:85afa5846628b01860aa36',
    messagingSenderId: '380903609347',
    projectId: 'amore-hk',
    authDomain: 'amore-hk.firebaseapp.com',
    storageBucket: 'amore-hk.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
} 