name: amore
description: "Amore - 專為香港市場設計的智能約會應用程式，連接 Gen Z 和 30-40 歲群體"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI 和動畫
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0
  
  # 路由管理
  go_router: ^12.1.3
  
  # 狀態管理
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # 網絡和 API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Firebase 服務
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_remote_config: ^4.3.8
  firebase_dynamic_links: ^5.4.8
  
  # 本地存儲
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 圖片處理
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # 約會/社交功能
  flutter_card_swiper: ^6.0.0
  
  # 工具類
  intl: ^0.20.2
  uuid: ^4.1.0
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  
  # JSON 序列化
  json_annotation: ^4.8.1
  
  # 加密和安全
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # 地理位置
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # 權限管理
  permission_handler: ^11.0.1
  
  # 本地化
  flutter_localizations:
    sdk: flutter

  # 視頻通話
  agora_rtc_engine: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # 資產配置
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    
  # 字體配置（使用系統字體暫時註釋）
  # fonts:
  #   - family: NotoSansTC
  #     fonts:
  #       - asset: assets/fonts/NotoSansTC-Regular.ttf
  #       - asset: assets/fonts/NotoSansTC-Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700 